# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts 'Seeding...'

User.create(name: 'Frank', username: 'frank', email: 'frank@email.com', password: 'Password1')
User.create(name: 'Deborah', username: 'deborah', email: 'deborah@email.com', password: 'Password1')
User.create(name: 'Charlie', username: 'charlie', email: 'charlie@email.com', password: 'Password1')
User.create(name: 'Mac', username: 'mac', email: 'mac@email.com', password: 'Password1')
User.create(name: 'Dee', username: 'dee', email: 'dee@email.com', password: 'Password1')
User.create(name: 'Dennis', username: 'dennis', email: 'dennis@email.com', password: 'Password1')
User.create(name: 'Harry', username: 'harry', email: 'harry@email.com', password: 'Password1')
User.create(name: 'Batista', username: 'batista', email: 'batista@email.com', password: 'Password1')

Event.create(title: 'Drinks with Frank', start: '2021-05-12 17:00', end: '2021-05-12 22:00', location: "Paddy's Pub", description: "Drinks at Paddy's for funsies", creator_id: 5)
Event.create(title: 'Rave in a Cave', start: '2021-08-01 16:00', end: '2021-08-01 23:59', location: 'Cave', description: 'Rave in a cave dub reggae stylee!', creator_id: 6)
Event.create(title: 'Few Bevvies with Batista', start: '2021-09-16 19:00', end: '2021-09-16 23:59', location: "Batista's Bar", description: "Couple of mojitos with Batista at his bar in Miami", creator_id: 12)
Event.create(title: 'Meet the Gang', start: '2021-07-29 12:00', end: '2021-07-29 23:59', location: "Paddy's Pub", description: "Go daytime drinking with the gang from It's allways sunny in Philidelphia", creator_id: 8)
Event.create(title: 'Beach Party', start: '2021-08-02 17:00', end: '2021-08-02 23:00', location: 'Hove Lawns', description: 'Beach party featuring Fatboy Slim!', creator_id: 1)

Invitation.create(event_id: 1, attendee_id: 2)
Invitation.create(event_id: 1, attendee_id: 3)
Invitation.create(event_id: 1, attendee_id: 4)
Invitation.create(event_id: 1, attendee_id: 5)
Invitation.create(event_id: 1, attendee_id: 6)
Invitation.create(event_id: 1, attendee_id: 7)
Invitation.create(event_id: 1, attendee_id: 8)
Invitation.create(event_id: 1, attendee_id: 9)
Invitation.create(event_id: 1, attendee_id: 10)
Invitation.create(event_id: 1, attendee_id: 11)
Invitation.create(event_id: 1, attendee_id: 12)

Invitation.create(event_id: 8, attendee_id: 2)
Invitation.create(event_id: 8, attendee_id: 3)
Invitation.create(event_id: 8, attendee_id: 4)
Invitation.create(event_id: 8, attendee_id: 5)
Invitation.create(event_id: 8, attendee_id: 6)
Invitation.create(event_id: 8, attendee_id: 7)
Invitation.create(event_id: 8, attendee_id: 8)
Invitation.create(event_id: 8, attendee_id: 9)
Invitation.create(event_id: 8, attendee_id: 10)
Invitation.create(event_id: 8, attendee_id: 11)
Invitation.create(event_id: 8, attendee_id: 12)

Invitation.create(event_id: 12, attendee_id: 2)
Invitation.create(event_id: 12, attendee_id: 3)
Invitation.create(event_id: 13, attendee_id: 4)
Invitation.create(event_id: 13, attendee_id: 5)
Invitation.create(event_id: 13, attendee_id: 6)
Invitation.create(event_id: 13, attendee_id: 7)
Invitation.create(event_id: 13, attendee_id: 8)
Invitation.create(event_id: 13, attendee_id: 9)
Invitation.create(event_id: 13, attendee_id: 10)
Invitation.create(event_id: 13, attendee_id: 11)
Invitation.create(event_id: 13, attendee_id: 12)

Invitation.create(event_id: 9, attendee_id: 2)
Invitation.create(event_id: 9, attendee_id: 3)
Invitation.create(event_id: 9, attendee_id: 4)
Invitation.create(event_id: 9, attendee_id: 5)
Invitation.create(event_id: 9, attendee_id: 6)
Invitation.create(event_id: 9, attendee_id: 7)
Invitation.create(event_id: 9, attendee_id: 8)
Invitation.create(event_id: 9, attendee_id: 9)
Invitation.create(event_id: 9, attendee_id: 10)
Invitation.create(event_id: 9, attendee_id: 11)
Invitation.create(event_id: 9, attendee_id: 12)

Invitation.create(event_id: 6, attendee_id: 2)
Invitation.create(event_id: 6, attendee_id: 3)
Invitation.create(event_id: 6, attendee_id: 4)
Invitation.create(event_id: 6, attendee_id: 5)
Invitation.create(event_id: 6, attendee_id: 6)
Invitation.create(event_id: 6, attendee_id: 7)
Invitation.create(event_id: 6, attendee_id: 8)
Invitation.create(event_id: 6, attendee_id: 9)
Invitation.create(event_id: 6, attendee_id: 10)
Invitation.create(event_id: 6, attendee_id: 11)
Invitation.create(event_id: 6, attendee_id: 12)

Invitation.create(event_id: 3, attendee_id: 2)
Invitation.create(event_id: 3, attendee_id: 3)
Invitation.create(event_id: 3, attendee_id: 4)
Invitation.create(event_id: 3, attendee_id: 5)
Invitation.create(event_id: 3, attendee_id: 6)
Invitation.create(event_id: 3, attendee_id: 7)
Invitation.create(event_id: 3, attendee_id: 8)
Invitation.create(event_id: 3, attendee_id: 9)
Invitation.create(event_id: 3, attendee_id: 10)
Invitation.create(event_id: 3, attendee_id: 11)
Invitation.create(event_id: 3, attendee_id: 12)

puts 'Seeding done.'
